proxy_cache_path /var/cache/nginx/chillflix_html levels=1:2 keys_zone=chillflix_html:64m max_size=1g inactive=10m;

map $http_cookie $chillflix_skip_html_cache {
    default 0;
    ~*chillflix_session 1;
}
